#Postgresql Configuration
spring.datasource.url=jdbc:postgresql://dpg-d9vaga6gekts73f6d710-a.singapore-postgres.render.com/money_manager_db_bnv1
spring.datasource.username=money_manager_db_bnv1
spring.datasource.password=hZXALpUs27ZX3Yo0mHSzCNQsqerbYZIQ
