#Postgresql Configuration
spring.datasource.url=jdbc:postgresql://dpg-daj82ah5efls73ftsl3g-a.singapore-postgres.render.com/money_manager_db_f3mt
spring.datasource.username=money_manager_db_f3mt_user
spring.datasource.password=tvMZA6NtkGmZBWy9pNo6d0Mp1FM8zs7P
