#Postgresql Configuration
spring.datasource.url=jdbc:postgresql://dpg-daj8kpgae00c7390gcg0-a.singapore-postgres.render.com/money_manager_db_r15t
spring.datasource.username=money_manager_db_r15t_user
spring.datasource.password=dc9HAY0raLc8w11JjVuH2pP9yqydLEA2
